name: Push to Replicate

on:
  workflow_dispatch:

jobs:
  push_to_replicate:
    name: Build & Push (Cog)
    runs-on: ubuntu-latest
    timeout-minutes: 240

    concurrency:
      group: replicate-push
      cancel-in-progress: true

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
          docker-images: false

      - name: Add swap (stability for nvcc builds)
        run: |
          set -euxo pipefail
          sudo fallocate -l 16G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        env:
          MAKEFLAGS: "-j1"
          CMAKE_BUILD_PARALLEL_LEVEL: "1"
          NINJAFLAGS: "-j1"
          MAX_JOBS: "1"
          TORCH_CUDA_ARCH_LIST: "8.0"
        run: |
          set -euxo pipefail
          cog push
