name: Push to Replicate

on:
  # Manual trigger from GitHub UI
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Optional. Format: username/model-name (e.g. simplesketche/trellis-2). If empty, uses image from cog.yaml.'
        required: false
        default: ''

  # Uncomment this block if you want auto-push on every commit to main
  # push:
  #   branches:
  #     - main

jobs:
  push_to_replicate:
    name: Build & Push Cog Model
    runs-on: ubuntu-latest

    steps:
      # Free disk space (important for large CUDA / model builds)
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true

      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Docker buildx + Cog CLI
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      # Push model to Replicate
      - name: Push to Replicate
        env:
          # Required for gated Hugging Face models (e.g. DINOv3)
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HUGGINGFACE_HUB_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Starting Cog push..."

          if [ -n "${{ inputs.model_name }}" ]; then
            echo "Using model name from input: ${{ inputs.model_name }}"
            cog push r8.im/${{ inputs.model_name }}
          else
            echo "Using image name from cog.yaml"
            cog push
          fi
